name: stats
channels:
  - conda-forge
  - pypi
dependencies:
  - streamlit
  - openai
  - langchain==0.0.70
  - PyPDF2==3.0.1
  - faiss-cpu==1.7.3
  - tiktoken==0.1.2
  - pdf2image
  - poppler
  - spacy==3.5.0
  - spacy-model-en_core_web_sm==3.5.0